"""init

Revision ID: d4031e4c35ad
Revises: 
Create Date: 2025-11-15 13:44:06.176795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4031e4c35ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giveaway_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('giveaway_about_title_uz', sa.String(length=255), nullable=False),
    sa.Column('giveaway_about_description_uz', sa.String(length=500), nullable=False),
    sa.Column('giveaway_about_title_ru', sa.String(length=255), nullable=False),
    sa.Column('giveaway_about_description_ru', sa.String(length=500), nullable=False),
    sa.Column('giveaway_about_title_en', sa.String(length=255), nullable=False),
    sa.Column('giveaway_about_description_en', sa.String(length=500), nullable=False),
    sa.Column('auto_join_title_uz', sa.String(length=255), nullable=False),
    sa.Column('auto_join_description_uz', sa.String(length=500), nullable=False),
    sa.Column('auto_join_title_ru', sa.String(length=255), nullable=False),
    sa.Column('auto_join_description_ru', sa.String(length=500), nullable=False),
    sa.Column('auto_join_title_en', sa.String(length=255), nullable=False),
    sa.Column('auto_join_description_en', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('promocode', sa.String(length=50), nullable=False),
    sa.Column('referal_promocode', sa.String(length=50), nullable=False),
    sa.Column('is_fake', sa.Boolean(), nullable=False),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('users')
    op.drop_table('giveaway_info')
    op.drop_table('channels')
    # ### end Alembic commands ###
